import image from "../assets/image.png";

const cardData = [
  {
    id: 1,
    title: "Large 4-room apartment with a beautiful terrace",
    price: "N 320 000",
    location: "Barcelona",
    image: image,
  },
  {
    id: 2,
    title: "Cozy 2-room flat in a prime location",
    price: "N 200 000",
    location: "Madrid",
    image: image,
  },
  {
    id: 3,
    title: "Modern 3-room penthouse with sea views",
    price: "N 450 000",
    location: "Ibiza",
    image: image,
  },
  {
    id: 4,
    title: "Spacious villa with a private pool",
    price: "N 1 200 000",
    location: "Malaga",
    image: image,
  },
  {
    id: 5,
    title: "Luxury 5-bedroom house with a garden",
    price: "N 850 000",
    location: "Valencia",
    image: image,
  },
  {
    id: 6,
    title: "Compact studio apartment near the city center",
    price: "N 150 000",
    location: "Seville",
    image: image,
  },
  {
    id: 7,
    title: "Elegant duplex with modern interiors",
    price: "N 600 000",
    location: "Granada",
    image: image,
  },
  {
    id: 8,
    title: "Family-friendly home with a large backyard",
    price: "N 500 000",
    location: "Bilbao",
    image: image,
  },
  {
    id: 9,
    title: "Penthouse with panoramic city views",
    price: "N 1 000 000",
    location: "Malaga",
    image: image,
  },
  {
    id: 10,
    title: "Beachfront villa with private beach access",
    price: "N 2 000 000",
    location: "Alicante",
    image: image,
  },
  {
    id: 11,
    title: "Urban loft with industrial-style design",
    price: "N 350 000",
    location: "Barcelona",
    image: image,
  },
  {
    id: 12,
    title: "Rustic countryside cottage with a fireplace",
    price: "N 280 000",
    location: "Toledo",
    image: image,
  },
  {
    id: 13,
    title: "Modern 2-bedroom flat near the university",
    price: "N 300 000",
    location: "Valencia",
    image: image,
  },
  {
    id: 14,
    title: "Historic home with traditional architecture",
    price: "N 550 000",
    location: "Cordoba",
    image: image,
  },
  {
    id: 15,
    title: "Apartment with rooftop access and BBQ area",
    price: "N 400 000",
    location: "Madrid",
    image: image,
  },
  {
    id: 16,
    title: "Eco-friendly house with solar panels",
    price: "N 900 000",
    location: "Malaga",
    image: image,
  },
  {
    id: 17,
    title: "Studio apartment with minimalist design",
    price: "N 200 000",
    location: "Barcelona",
    image: image,
  },
  {
    id: 18,
    title: "Classic townhouse in a peaceful neighborhood",
    price: "N 750 000",
    location: "Seville",
    image: image,
  },
];

export default cardData;
